name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      uses: docker/setup-qemu-action@v2

    - name: Ensure Docker Compose is available
      run: docker-compose version

    - name: Create .env file dynamically
      run: |
          echo "DATABASE_URL=postgresql://postgres:mysecretpassword@localhost:5432/postgres" > ./server/.env
          echo "PORT=3001" >> ./server/.env
          echo "JWT_SECRET=randompassword" >> ./server/.env
          echo "POSTGRES_USER=postgres" >> ./server/.env
          echo "POSTGRES_PASSWORD=mysecretpassword" >> ./server/.env
          echo "POSTGRES_DB=postgres" >> ./server/.env

    - name: Run integration script
      run: cd server && npm run test:integration
