name: CI/CD Pipeline

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Ensure Docker Compose is available
      run: docker-compose version

    - name: Copy .env.example to .env
      run: cp ./server/.env.example ./server/.env

    - name: Run integration script
      run: cd server && npm run test:integration